Feature/refactor psp1155
Supercolony-net/openbrush-contracts pull request #119
Opened 2022-05-24 14:11 UTC by Artemka374

2022-05-24 17:49 UTC, coreggon11 reviewed
gj

you can change the version of OB to 1.7.0 and ink version to 3.1.0 everywhere since it is in a PR

also please add Batch extensions to docs

2022-05-24 17:49 UTC, coreggon11 commented on contracts/traits/psp35/extensions/batch.rs
> +use crate::traits::psp35::Id;
please format

2022-05-24 17:49 UTC, coreggon11 commented on contracts/token/psp35/psp35.rs
> +        let id_opt = Some(id);
do you need this variable?

2022-05-24 17:49 UTC, coreggon11 commented on contracts/token/psp35/psp35.rs
> +        }
```suggestion
        return match self.get().operator_approvals.get(&(owner, operator, None)) {
            None => self.get().operator_approvals.get(&(owner, operator, id)).unwrap_or(0),
            Some(value) => value            
        }
```

2022-05-24 17:49 UTC, coreggon11 commented on contracts/token/psp35/psp35.rs
> +        if caller == operator {
this check is not needed imo,
if so we should return a different error

2022-05-24 17:49 UTC, coreggon11 commented on contracts/token/psp35/psp35.rs
> +        let operator = Self::env().caller();
we dont need these since we use them only once

2022-05-26 10:15 UTC, coreggon11 reviewed
left few more comments

2022-05-26 10:15 UTC, coreggon11 commented on docs/docs/smart-contracts/PSP35/Extensions/batch.md
> +This example shows how you can reuse the implementation of [PSP35](https://github.com/Supercolony-net/openbrush-contracts/tree/main/contracts/token/psp35) token with [PSP35Batch](https://github.com/S
```suggestion
This example shows how you can reuse the implementation of [PSP35](https://github.com/Supercolony-net/openbrush-contracts/tree/main/contracts/token/psp35) token with [PSP35Batch](https://github.com/Supercolony-net/openbrush-contracts/tree/main/contracts/token/psp35/src/extensions/batch.rs) extension, which allows batch transferring of PSP35 tokens.
```

2022-05-26 10:15 UTC, coreggon11 commented on docs/docs/smart-contracts/PSP35/psp35.md
> +    psp25: PSP35Data,
```suggestion
    #[PSP35StorageField]
    psp35: PSP35Data,
```

2022-05-26 10:15 UTC, coreggon11 commented on docs/docs/smart-contracts/overview.md
> +  * [PSP35Batch](PSP35/Extensions/batch.md): transfer a batch of tokens
```suggestion
  * [PSP35Batch](PSP35/Extensions/batch.md): batch transferring of tokens
```

2022-05-26 10:15 UTC, coreggon11 commented on examples/psp35_extensions/batch/README.md
> +Implementation of [EIP-1155](https://eips.ethereum.org/EIPS/eip-1155) token standard with batch extension in Polkadot blockchain that allows to transfer a batch of tokens.
```suggestion
Implementation of [EIP-1155](https://eips.ethereum.org/EIPS/eip-1155) token standard with batch extension in Polkadot blockchain that allows batch transferring of tokens.
```

2022-05-26 19:58 UTC, coreggon11 approved these changes

2022-06-06 12:55 UTC, xgreenx requested changes

2022-06-06 12:55 UTC, xgreenx commented on contracts/src/traits/psp35/psp35.rs
> +    /// Allows `operator` to withdraw  the `id` token from the caller's account
Comment is not actual

2022-06-06 12:55 UTC, xgreenx commented on contracts/src/traits/psp35/psp35.rs
> +    fn allowance(&self, owner: AccountId, operator: AccountId, id: Option<Id>) -> Balance;
Missed comment

2022-06-06 12:55 UTC, xgreenx commented on contracts/src/traits/psp35/psp35.rs
> +    fn transfer(&mut self, to: AccountId, id: Id, value: Balance, data: Vec<u8>) -> Result<(), PSP35Error>;
Missed comment

2022-06-06 12:55 UTC, xgreenx commented on docs/docs/smart-contracts/PSP22/Extensions/burnable.md
> +You can check an example of the usage of [PSP22 Burnable](https://github.com/Supercolony-net/openbrush-contracts/tree/master/examples/psp22_extensions/burnable).
Return back usage of `main` please=)

2022-06-06 12:55 UTC, xgreenx commented on docs/docs/smart-contracts/PSP35/Extensions/metadata.md
> +Import **everything** from `brush::contracts::psp35::extensions::metadata`.
You need to update documentation to use `openbrush` instead of `brush` everywhere=)

2022-06-06 12:55 UTC, xgreenx commented on docs/docs/smart-contracts/PSP35/psp35.md
> +brush = { tag = "v1.7.0", git = "https://github.com/Supercolony-net/openbrush-contracts", default-features = false, features = ["psp1155"] }
You need to adapt the documentation and use a new feature `psp35` instead of `psp1155`.

2022-06-06 12:55 UTC, xgreenx commented on docs/docs/smart-contracts/PSP35/psp35.md
> +pub mod my_psp1155 {
Wrong naming

2022-06-06 12:55 UTC, xgreenx commented on examples/psp35_extensions/metadata/lib.rs
> +                instance.metadata.attributes.insert(&(id, key), &attribute);
We can add internal methods `_set_attribute` and `_get_attribute` that work with references.

2022-06-06 12:55 UTC, xgreenx commented on tests/e2e/psp35/extensions/metadata.tests.ts
> +    await expect(query.getAttribute(bnArg(0), bnArg(1))).to.have.output(bnArg(encoder.encode('https://www.supercolony.net/')))
Let's add the `set_attribtue` public method to the example and yet it too.

2022-06-06 12:55 UTC, xgreenx commented on tests/psp35.rs
> +    fn transfer() {
Could you test transfer from not approved account, please?=)

2022-06-06 12:55 UTC, xgreenx commented on tests/psp35_burnable.rs
> -    fn after_token_transfer_should_fail_burn() {
Why did we remove that test?=)

2022-06-06 12:55 UTC, xgreenx commented on tests/psp35_mintable.rs
> -    fn after_token_transfer_should_fail_mint() {
Why did we remove that test?=)

2022-06-06 12:55 UTC, xgreenx commented on utils/brush_lang/Cargo.toml
> +[package]
Seems you can remove it, artifact of the merge=D

2022-06-12 15:31 UTC, xgreenx approved these changes

2022-06-12 15:31 UTC, merged