Ownable-PSP1155 example
Supercolony-net/openbrush-contracts pull request #15
Opened 2021-06-23 15:03 UTC by PierreOssun

2021-06-23 15:20 UTC, xgreenx requested changes

2021-06-23 15:20 UTC, xgreenx commented on tests/ownable.tests.ts
> +    await expect(query.balanceOf(alice.address, bnArg(0))).to.have.output(20)
You can check it via batch balance of

2021-06-23 15:20 UTC, xgreenx commented on tests/ownable.tests.ts
> +  it('PSP 1155 - mint works', async () => {
You also need to verify `is_approved_for_all`, `set_approval_for_all`, and both "safe" functions(for that you need to deploy a mock Receiver and verify that on_received was called).

About safe methods. Could you also add the same test for PSP721 please?

2021-06-23 15:25 UTC, VargSupercolony reviewed
clear for me, change according to Green and my approval is there

2021-06-23 15:25 UTC, VargSupercolony commented on contracts/token/psp1155/traits.rs
> +    /// Creates a new token.
I guess it doesn't really create a new token per say, it just 'mints' it (increases the emission), just like 'burn' below doesn't delete the token, just decreases the emission/supply

2021-06-25 07:44 UTC, xgreenx approved these changes

2021-06-25 07:44 UTC, xgreenx commented on examples/ownable/lib.rs
> +            self.only_owner();
You can use modifiers macro here

2021-06-25 07:44 UTC, xgreenx commented on tests/access-control.tests.ts
> +  it('PSP 721 - safe transfer works', async () => {
Will be cool to test the scenario where the Receiver will reject the transfer to verify that it works properly.

For that, you can add an additional method to mock contract `revert_next_transfer()`

2021-06-25 10:06 UTC, xgreenx requested changes

2021-06-25 10:06 UTC, xgreenx commented on mock/psp1155-receiver/lib.rs
> +                return Err(PSP1155ReceiverError::TransferRejected)
You need to do it `self.revert_next_transfer = false;` here=)

2021-06-25 10:06 UTC, xgreenx commented on contracts/token/psp721/traits.rs
> +    TransferRejected,
Please return back the string=)

2021-06-25 12:00 UTC, xgreenx approved these changes

2021-06-25 12:00 UTC, xgreenx commented on mock/psp1155-receiver/lib.rs
> +            self.revert_next_transfer = false;
You can remove this line and in PSP721 too=)

2021-06-25 13:11 UTC, PierreOssun commented on contracts/token/psp1155/traits.rs
>      /// Returns the URI for token type `id`.
I was wondering if we should remove both or add it in erc1155. Adding it !

2021-06-25 13:22 UTC, xgreenx approved these changes

2021-06-29 07:59 UTC, merged