Fixed indexation of storage traits
Supercolony-net/openbrush-contracts pull request #16
Opened 2021-06-23 15:07 UTC by xgreenx

Inherited InkStorage for all contracts.
Created STUB derive macros to enable indexing of traits.

2021-06-23 15:42 UTC, VargSupercolony requested changes
naming suggestions

2021-06-23 15:42 UTC, VargSupercolony commented on contracts/access/access-control/Cargo.toml
> +access_controll_macro = { path = "./macro" }
change access_controll_macro to access_control_macro - a little spelling error

2021-06-23 15:42 UTC, VargSupercolony commented on contracts/token/psp1155/macro/Cargo.toml
> +name = "psp1155_macro"
pls rename to psp1155_derive - that's the standard naming of derive macro crates

2021-06-23 15:42 UTC, VargSupercolony commented on contracts/access/access-control/macro/Cargo.toml
> +name = "access_controll_macro"
rename to access_control_derive

2021-06-23 15:42 UTC, VargSupercolony commented on contracts/token/psp20/macro/Cargo.toml
> +name = "psp20_macro"
rename to psp20_derive

2021-06-23 15:42 UTC, VargSupercolony commented on contracts/token/psp721/macro/Cargo.toml
> +name = "psp721_macro"
rename psp721_macro -> psp721_derive

2021-06-23 16:31 UTC, VargSupercolony approved these changes
great work: created derive macros for traits to fix indexing and make code completion (presentation compiler) work

2021-06-24 07:40 UTC, PierreOssun approved these changes
Ok for me

2021-06-24 09:32 UTC, merged