Preparations for milestone 1 delivery report
Supercolony-net/openbrush-contracts pull request #28
Opened 2021-07-29 23:41 UTC by xgreenx

Formatted code.
Added comments for Ownable, AccessControl.
Updated comments for PSP721 and PSP1155.

2021-07-30 13:16 UTC, sventime approved these changes

2021-07-30 13:53 UTC, VargSupercolony requested changes
Reformat project to look pretty :3

2021-07-30 13:53 UTC, VargSupercolony commented on contracts/access/access-control/traits.rs
> +/// The AccessControl error type. Contract will assert one of this errors.
```suggestion
/// The AccessControl error type. Contract will throw one of this errors.
```

2021-07-30 13:53 UTC, VargSupercolony commented on contracts/access/access-control/traits.rs
> +/// The AccessControl error type. Contract will assert one of this errors.
or other more suitable word

2021-07-30 13:53 UTC, VargSupercolony commented on examples/reentrancy_guard/README.md
> +modifier to prevent reentrancy into certain functions. In this example we will create two contract:
```suggestion
modifier to prevent reentrancy into certain functions. In this example we will create two contracts:
```

2021-08-02 07:24 UTC, VargSupercolony approved these changes
Reformat code to look pretty

2021-08-02 09:24 UTC, merged