WIP: Support for ink! 3.0.0-rc8
Supercolony-net/openbrush-contracts pull request #78
Opened 2022-02-07 17:47 UTC by yarikbratashchuk

🚧  WIP 🚧 
Ended up here:
```
  --> contracts/tests/pausable.rs:43:9
   |
43 |         #[brush::modifiers(when_paused)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ink_env::call::CallBuilder`, found enum `Result`
44 |         pub fn flip(&mut self) -> Result<bool, PausableError> {
   |                                   --------------------------- expected `ink_env::call::CallBuilder<DefaultEnvironment, Set<ink_env::AccountId>, Unset<u64>, Unset<u128>, Set<ExecutionInput<ArgumentList<ArgumentListEnd, ArgumentListEnd>>>, Set<ReturnType<Result<bool, contracts::pausable::PausableError>>>>` because of return type
   |
   = note: expected struct `ink_env::call::CallBuilder<DefaultEnvironment, Set<ink_env::AccountId>, Unset<u64>, Unset<u128>, Set<ExecutionInput<ArgumentList<ArgumentListEnd, ArgumentListEnd>>>, Set<ReturnType<Result<bool, contracts::pausable::PausableError>>>>`
                found enum `Result<_, _>`

error[E0277]: the trait bound `MyFlipperRef: contracts::pausable::PausableStorage` is not satisfied
  --> contracts/tests/pausable.rs:43:28
   |
43 |         #[brush::modifiers(when_paused)]
   |                            ^^^^^^^^^^^ the trait `contracts::pausable::PausableStorage` is not implemented for `MyFlipperRef`
   |
note: required by a bound in `contracts::pausable::when_paused`
  --> /Users/yarik/work/supercolony/openbrush-contracts/contracts/security/pausable/mod.rs:26:8
   |
26 |     T: PausableStorage,
   |        ^^^^^^^^^^^^^^^ required by this bound in `contracts::pausable::when_paused`
```

2022-02-07 21:26 UTC, xgreenx commented
You also will be useful to check that PR: https://github.com/Supercolony-net/openbrush-contracts/pull/49/files

2022-02-19 15:59 UTC, yarikbratashchuk commented
Okay, I'm leaving it as it is.
My contribution to this was insignificant anyway. 
Now what is needed is to build a working Europa node and make redspot tests pass.

2022-02-21 09:44 UTC, VargSupercolony requested changes
great work! left a couple of comments.

2022-02-21 09:44 UTC, VargSupercolony commented on examples/psp1155/lib.rs
>      }
Maybe we could use some lightweight collection here? As we only need keys some `Set` would be ideal

2022-02-28 10:10 UTC, coreggon11 approved these changes

2022-02-28 10:17 UTC, PierreOssun approved these changes
Great work!

2022-02-28 10:37 UTC, xgreenx commented on Cargo.toml
>  edition = "2018"
It is `2018` because it doesn't work correctly with tests and `--all-features` with `2021`.

2022-03-01 11:27 UTC, merged